#!/usr/bin/env python3
"""Offline self-test for the Phase-3 stereo calibration math core.

NO device, NO checkerboard photos: we synthesize a ground-truth (GT) stereo rig +
a planar board at diverse poses, project the board's 3D corners into BOTH cameras
with ``cv2.projectPoints`` (using the GT intrinsics/distortion and the GT LEFT->RIGHT
transform), and feed those synthetic image points to the solver -- then assert it
RECOVERS the GT. Because the data is generated by the SAME forward model cv2
inverts, we also add Gaussian pixel noise and re-check under a looser tolerance, so
a pass proves a real fit, not a trivial round-trip of a noiseless model.

Three gates:
  1. Synthetic-board recovery (THE key gate) -- noiseless + noisy. Plus two NEGATIVE
     sub-tests that PROVE the recovery check has teeth: injecting a transposed R
     (R := R.T) and a negated T (T := -T) into a correct solve must each FAIL the
     extrinsic-direction guard, so a real LEFT<->RIGHT swap in solve.py cannot slip
     through the thresholds.
  2. Collector logic -- accepts diverse views, rejects a near-duplicate, rejects a
     one-camera detection failure; an all-FRONTO-PARALLEL sweep reaches n_target
     accepted but is NOT complete (tilt coverage insufficient), while a genuinely
     TILTED + diverse sweep reaches n_target AND completes.
  3. Writer round-trip -- reload via StereoCalib.from_json (proves the cm/m factor)
     and run the shipped calib_check suite on the written file (must PASS).

cv2 appears HERE ONLY as the dev/test forward-model + detection oracle -- never in
the calib package's import path (asserted in test_package_import_is_cv2_free).

Run:  .venv/bin/python -m ui.tests.calib_solve_selftest
"""
from __future__ import annotations

import dataclasses
import json
import sys
import tempfile
from pathlib import Path

import cv2          # dev/test ORACLE + forward model only -- never in the calib pkg
import numpy as np

from imu_camera.io.reader import StereoCalib
from imu_camera.tools.calib_check import FAIL, run_checks
from ui.mathlib.calib.checkerboard import make_checkerboard
from sky.calib.collector import CollectorConfig, StereoCheckerboardCollector
from sky.calib.detect import reconcile_lr
from sky.calib.solve import solve_stereo
from sky.calib.writer import calib_to_dict, write_calib_json

# --------------------------------------------------------------------------- #
# Ground truth: OAK-D-like 640x400, fx~=fy~=285, mild distortion, 7.5 cm baseline.
# --------------------------------------------------------------------------- #
PATTERN_COLS, PATTERN_ROWS = 9, 6
SQUARE_SIZE_M = 0.025                  # 25 mm squares
IMAGE_SIZE = (640, 400)               # (width, height)
GT_BASELINE_M = 0.075

GT_K_L = np.array([[285.0, 0.0, 320.0],
                   [0.0, 286.0, 200.0],
                   [0.0, 0.0, 1.0]], dtype=np.float64)
GT_K_R = np.array([[284.0, 0.0, 318.0],
                   [0.0, 285.0, 201.0],
                   [0.0, 0.0, 1.0]], dtype=np.float64)
# Mild radial/tangential distortion (k1,k2,p1,p2,k3) -- realistic for a wide lens.
GT_DIST_L = np.array([-0.045, 0.012, 0.0006, -0.0004, 0.0], dtype=np.float64)
GT_DIST_R = np.array([-0.040, 0.010, 0.0005, -0.0003, 0.0], dtype=np.float64)

# GT LEFT->RIGHT extrinsic: a near-parallel rig translated ~75 mm along -X (the
# right camera sits to the right of the left, so a left-frame point lands at more
# negative X in the right frame), with a deliberate rotation so the test can detect
# a flipped/transposed extrinsic (a pure-translation T is direction-blind). The
# angle is 2.5 deg -- a realistic stereo-rig yaw misalignment, and large enough that
# a TRANSPOSED R is geometrically distinct: ||R.T - R|| ~= 2*sin(2.5 deg) ~= 0.087,
# well above the tightened R_err < 5e-3 recovery threshold, so a LEFT<->RIGHT
# transpose bug in the solver can no longer slip past the flip-guard.
_ang = np.deg2rad(2.5)
GT_R_LR = np.array([[np.cos(_ang), 0.0, np.sin(_ang)],
                    [0.0, 1.0, 0.0],
                    [-np.sin(_ang), 0.0, np.cos(_ang)]], dtype=np.float64)
GT_T_LR = np.array([-GT_BASELINE_M, 0.0, 0.0], dtype=np.float64)  # metres, LEFT->RIGHT


def _object_points() -> np.ndarray:
    """GT board corners in the board frame (Z=0), metres -- detector raster order."""
    obj = np.zeros((PATTERN_ROWS * PATTERN_COLS, 3), dtype=np.float64)
    grid = np.mgrid[0:PATTERN_COLS, 0:PATTERN_ROWS].T.reshape(-1, 2)
    obj[:, :2] = grid
    return obj * SQUARE_SIZE_M


def _board_poses() -> list[tuple[np.ndarray, np.ndarray]]:
    """~15 DIVERSE board poses (rvec, tvec) in the LEFT camera frame.

    Varied distance (0.4-0.9 m), in-frame translation (board centroid swept around
    the image), and tilt (rotation) so the views cover the calibration space.
    """
    poses: list[tuple[np.ndarray, np.ndarray]] = []
    # Centre the board roughly: half the board's metric extent.
    bx = (PATTERN_COLS - 1) * SQUARE_SIZE_M * 0.5
    by = (PATTERN_ROWS - 1) * SQUARE_SIZE_M * 0.5
    # (depth, x_off, y_off, rx_deg, ry_deg, rz_deg) -- 15 diverse poses.
    specs = [
        (0.50, 0.00, 0.00, 0, 0, 0),
        (0.45, -0.06, -0.04, 12, -8, 3),
        (0.55, 0.07, -0.03, -10, 10, -5),
        (0.60, -0.05, 0.05, 8, 14, 6),
        (0.40, 0.04, 0.04, -14, -12, -4),
        (0.65, 0.08, -0.06, 5, -18, 8),
        (0.70, -0.08, 0.06, -6, 16, -10),
        (0.48, 0.03, -0.05, 18, 4, 2),
        (0.58, -0.07, -0.02, -12, -6, 12),
        (0.62, 0.06, 0.05, 9, -14, -7),
        (0.52, -0.04, 0.03, -16, 9, 5),
        (0.44, 0.05, -0.04, 14, 12, -9),
        (0.68, -0.06, -0.05, -8, -16, 4),
        (0.56, 0.07, 0.04, 11, 7, -6),
        (0.50, -0.03, 0.06, -13, -10, 10),
    ]
    for depth, xo, yo, rx, ry, rz in specs:
        # Compose the board orientation from XYZ Euler tilts.
        rot_deg = np.array([rx, ry, rz], dtype=np.float64)
        rvec, _ = cv2.Rodrigues(_euler_xyz_to_R(np.deg2rad(rot_deg)))
        # Place the board so its centre is near (xo, yo, depth) in the left frame.
        tvec = np.array([xo - bx, yo - by, depth], dtype=np.float64).reshape(3, 1)
        poses.append((rvec.reshape(3), tvec.reshape(3)))
    return poses


def _euler_xyz_to_R(rpy: np.ndarray) -> np.ndarray:
    """Rotation from XYZ Euler angles (rad) -- local helper for pose synthesis."""
    rx, ry, rz = rpy
    cx, sx = np.cos(rx), np.sin(rx)
    cy, sy = np.cos(ry), np.sin(ry)
    cz, sz = np.cos(rz), np.sin(rz)
    Rx = np.array([[1, 0, 0], [0, cx, -sx], [0, sx, cx]])
    Ry = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]])
    Rz = np.array([[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]])
    return Rz @ Ry @ Rx


def _project_views(noise_px: float = 0.0, seed: int = 0
                   ) -> list[tuple[np.ndarray, np.ndarray]]:
    """Project the GT board at every pose into BOTH cameras -> per-view L/R corners.

    The right-camera projection composes the board->left pose with the GT
    LEFT->RIGHT transform, so the synthetic right points encode the GT extrinsic --
    recovering it back proves the solver's T_left_right direction.
    """
    rng = np.random.default_rng(seed)
    obj = _object_points()
    views: list[tuple[np.ndarray, np.ndarray]] = []
    for rvec, tvec in _board_poses():
        R_bl, _ = cv2.Rodrigues(rvec)            # board -> left
        t_bl = tvec.reshape(3, 1)

        # LEFT image points: project board with the board->left pose.
        img_l, _ = cv2.projectPoints(obj, rvec, t_bl, GT_K_L, GT_DIST_L)

        # RIGHT image points: chain board->left then left->right.
        # X_right = R_LR @ (R_bl @ X_board + t_bl) + t_LR
        R_br = GT_R_LR @ R_bl
        t_br = (GT_R_LR @ t_bl).reshape(3) + GT_T_LR
        rvec_br, _ = cv2.Rodrigues(R_br)
        img_r, _ = cv2.projectPoints(
            obj, rvec_br, t_br.reshape(3, 1), GT_K_R, GT_DIST_R)

        cl = img_l.reshape(-1, 2).astype(np.float64)
        cr = img_r.reshape(-1, 2).astype(np.float64)
        if noise_px > 0.0:
            cl = cl + rng.normal(0.0, noise_px, cl.shape)
            cr = cr + rng.normal(0.0, noise_px, cr.shape)
        views.append((cl.astype(np.float32), cr.astype(np.float32)))
    return views


# --------------------------------------------------------------------------- #
# Gate 1: synthetic-board recovery.
# --------------------------------------------------------------------------- #
def _assert_recovers(result, *, k_tol_frac: float, baseline_tol_m: float,
                     rms_tol_px: float, label: str) -> None:
    """Assert the solved result recovers the GT intrinsics, baseline, direction."""
    # --- intrinsics (fx, fy, cx, cy) within k_tol_frac, both cameras ---
    for name, K_gt, K_got in (("L", GT_K_L, result.K_l), ("R", GT_K_R, result.K_r)):
        for idx, lbl in (((0, 0), "fx"), ((1, 1), "fy"), ((0, 2), "cx"), ((1, 2), "cy")):
            gt = K_gt[idx]
            got = K_got[idx]
            rel = abs(got - gt) / abs(gt)
            assert rel <= k_tol_frac, (
                f"[{label}] {name}.{lbl}: got {got:.3f} vs GT {gt:.3f} "
                f"(rel {rel * 100:.3f}% > {k_tol_frac * 100:.2f}%)")

    # --- baseline magnitude ---
    base = result.baseline_m
    assert abs(base - GT_BASELINE_M) <= baseline_tol_m, (
        f"[{label}] baseline {base * 1000:.3f} mm vs GT {GT_BASELINE_M * 1000:.1f} "
        f"mm (err {abs(base - GT_BASELINE_M) * 1000:.3f} mm > "
        f"{baseline_tol_m * 1000:.3f} mm)")

    # --- EXTRINSIC DIRECTION: recovered T_left_right must match the GT LEFT->RIGHT
    #     transform, NOT its inverse (the silent-bug guard). Compare both R and t. ---
    T_got = result.T_left_right
    R_err = float(np.linalg.norm(T_got[:3, :3] - GT_R_LR))
    t_err = float(np.linalg.norm(T_got[:3, 3] - GT_T_LR))
    # The INVERSE (right->left) would give t ~= -GT_T_LR; assert we are NOT that.
    t_err_if_flipped = float(np.linalg.norm(T_got[:3, 3] - (-GT_T_LR)))
    assert t_err < t_err_if_flipped, (
        f"[{label}] T_left_right looks FLIPPED: ||t-GT||={t_err:.4f} is not "
        f"smaller than ||t-(-GT)||={t_err_if_flipped:.4f}")
    # R_err threshold tightened to 5e-3: the true noiseless recovery is ~7e-8 and the
    # noisy-0.2px recovery is ~2e-3, so 5e-3 holds with margin -- yet it is far below
    # the ||R.T - R|| ~= 0.087 a transposed extrinsic would produce at this 2.5 deg
    # GT rotation, so a LEFT<->RIGHT transpose bug now FAILS this arm (the negative
    # sub-test in test_extrinsic_transpose_is_caught proves the guard has teeth).
    assert R_err < 5e-3 and t_err < baseline_tol_m * 2, (
        f"[{label}] extrinsic mismatch: R_err={R_err:.4e} t_err={t_err * 1000:.3f} mm")

    # --- reprojection RMS: stereo AND per-camera mono fits must be tight ---
    assert result.stereo_rms <= rms_tol_px, (
        f"[{label}] stereo RMS {result.stereo_rms:.4f} px > {rms_tol_px:.3f} px")
    assert result.rms_l <= rms_tol_px, (
        f"[{label}] mono-LEFT RMS {result.rms_l:.4f} px > {rms_tol_px:.3f} px")
    assert result.rms_r <= rms_tol_px, (
        f"[{label}] mono-RIGHT RMS {result.rms_r:.4f} px > {rms_tol_px:.3f} px")

    print(f"[ok] recovery {label}:")
    print(f"       K_l fx/fy/cx/cy = {result.K_l[0,0]:.3f}/{result.K_l[1,1]:.3f}/"
          f"{result.K_l[0,2]:.3f}/{result.K_l[1,2]:.3f}  "
          f"(GT {GT_K_L[0,0]:.1f}/{GT_K_L[1,1]:.1f}/{GT_K_L[0,2]:.1f}/{GT_K_L[1,2]:.1f})")
    print(f"       K_r fx/fy/cx/cy = {result.K_r[0,0]:.3f}/{result.K_r[1,1]:.3f}/"
          f"{result.K_r[0,2]:.3f}/{result.K_r[1,2]:.3f}  "
          f"(GT {GT_K_R[0,0]:.1f}/{GT_K_R[1,1]:.1f}/{GT_K_R[0,2]:.1f}/{GT_K_R[1,2]:.1f})")
    print(f"       baseline = {base * 1000:.4f} mm (GT {GT_BASELINE_M * 1000:.1f} mm, "
          f"err {abs(base - GT_BASELINE_M) * 1000:.4f} mm)")
    print(f"       extrinsic R_err={R_err:.3e}  t_err={t_err * 1000:.4f} mm "
          f"(flip-guard: ||t-(-GT)||={t_err_if_flipped * 1000:.2f} mm)")
    print(f"       RMS  mono L/R = {result.rms_l:.4f}/{result.rms_r:.4f} px  "
          f"stereo = {result.stereo_rms:.4f} px")


def test_synthetic_recovery_noiseless() -> None:
    """THE key gate: recover GT from noiseless synthetic projections, tightly."""
    views = _project_views(noise_px=0.0)
    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    _assert_recovers(result, k_tol_frac=0.01, baseline_tol_m=0.001,
                     rms_tol_px=0.05, label="noiseless")


def test_synthetic_recovery_noisy() -> None:
    """Add 0.2 px Gaussian noise: must still recover under a looser-but-sane bound."""
    views = _project_views(noise_px=0.2, seed=7)
    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    _assert_recovers(result, k_tol_frac=0.02, baseline_tol_m=0.002,
                     rms_tol_px=0.5, label="noisy(0.2px)")


# --------------------------------------------------------------------------- #
# Gate 1c: WIDE-FISHEYE recovery -- the OAK-D W regression. THE gap that let the
# real-device bug through (fx ran away to 1884, stereo RMS diverged to 1e13). The
# existing recovery tests use a MILD ~5 deg-of-distortion pinhole, which the default
# 5-coeff model fits fine, so they never exercise the wide lens. Here we synthesize a
# WIDE rig (fx=fy~=260 => ~101 deg HFOV) with STRONG barrel distortion expressed in the
# 8-coeff RATIONAL model (the model the OAK-D factory calib is a near-superset of),
# project the board through it, and assert solve_stereo RECOVERS fx~=260 (NOT 1884), a
# baseline within a few mm, and a sane stereo RMS -- i.e. the rational model + seeded
# intrinsic guess no longer let the focal length run away on a wide lens.
# --------------------------------------------------------------------------- #
# Wide GT: 640x400, fx=fy~=260 (HFOV ~= 2*atan(320/260) ~= 101 deg -- a real wide lens),
# strong barrel distortion as an 8-coeff rational set (dominant negative k1 + the high-
# order k4..k6 terms the 5-coeff model cannot represent). 7.5 cm baseline, 2.5 deg yaw.
WIDE_K_L = np.array([[260.0, 0.0, 320.0],
                     [0.0, 261.0, 200.0],
                     [0.0, 0.0, 1.0]], dtype=np.float64)
WIDE_K_R = np.array([[259.0, 0.0, 318.0],
                     [0.0, 260.0, 201.0],
                     [0.0, 0.0, 1.0]], dtype=np.float64)
# 8-coeff rational distortion (k1,k2,p1,p2,k3,k4,k5,k6) -- a strong wide barrel.
WIDE_DIST_L = np.array([-0.35, 0.14, 0.0003, -0.0002, -0.03, 0.06, -0.012, 0.005],
                       dtype=np.float64)
WIDE_DIST_R = np.array([-0.34, 0.13, 0.0002, -0.0001, -0.028, 0.055, -0.011, 0.0045],
                       dtype=np.float64)


def _project_wide_views(dist_l: np.ndarray = WIDE_DIST_L,
                        dist_r: np.ndarray = WIDE_DIST_R
                        ) -> list[tuple[np.ndarray, np.ndarray]]:
    """Project the board through the WIDE GT rig into both cameras (per-view L/R).

    Same diverse poses + LEFT->RIGHT chaining as :func:`_project_views`, but with the
    WIDE intrinsics + strong rational distortion. ``dist_l/dist_r`` are overridable so
    the outlier test can corrupt a single view's RIGHT distortion to inject a bad board.
    """
    obj = _object_points()
    views: list[tuple[np.ndarray, np.ndarray]] = []
    for rvec, tvec in _board_poses():
        R_bl, _ = cv2.Rodrigues(rvec)
        t_bl = tvec.reshape(3, 1)
        img_l, _ = cv2.projectPoints(obj, rvec, t_bl, WIDE_K_L, dist_l)
        R_br = GT_R_LR @ R_bl
        t_br = (GT_R_LR @ t_bl).reshape(3) + GT_T_LR
        rvec_br, _ = cv2.Rodrigues(R_br)
        img_r, _ = cv2.projectPoints(
            obj, rvec_br, t_br.reshape(3, 1), WIDE_K_R, dist_r)
        cl = img_l.reshape(-1, 2).astype(np.float32)
        cr = img_r.reshape(-1, 2).astype(np.float32)
        views.append((cl, cr))
    return views


def test_wide_fisheye_recovery() -> None:
    """THE OAK-D W gate: recover fx~=260 (NOT 1884) from a WIDE strongly-distorted rig.

    Asserts the solver returns the wide focal length, a baseline within a few mm of the
    GT, and a sane (non-diverged) stereo RMS -- the exact failure the real device hit.
    Also asserts the recovered fx is FAR from the runaway value the old default model
    produced (~1884), so a regression to the un-seeded 5-coeff model fails this test.
    """
    views = _project_wide_views()
    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)

    assert result.ok, f"wide solve should converge, got: {result.failure_reason}"
    # fx recovered to the WIDE truth (~260), NOT the runaway ~1884 the bug produced.
    fx_l, fx_r = float(result.K_l[0, 0]), float(result.K_r[0, 0])
    for name, fx, gt in (("L", fx_l, 260.0), ("R", fx_r, 259.0)):
        rel = abs(fx - gt) / gt
        assert rel <= 0.02, (
            f"wide {name} fx={fx:.2f} not within 2% of GT {gt:.1f} (rel {rel*100:.2f}%)")
    # Hard guard on the SPECIFIC failure: fx must be nowhere near the 1884 runaway.
    assert fx_l < 600.0 and fx_r < 600.0, (
        f"focal length ran away (wide-FOV bug): fx_l={fx_l:.1f} fx_r={fx_r:.1f} "
        f"(the regression produced ~1884)")
    # fx/width must sit in the wide-lens band, never the runaway ~2.9.
    assert 0.2 <= fx_l / IMAGE_SIZE[0] <= 2.0, fx_l / IMAGE_SIZE[0]

    # Baseline within a few mm of the GT 75 mm (the bug gave ~961 mm).
    base_mm = result.baseline_m * 1000.0
    assert abs(base_mm - 75.0) <= 5.0, (
        f"wide baseline {base_mm:.2f} mm not within 5 mm of GT 75 mm "
        f"(the bug produced ~961 mm)")
    # Stereo RMS sane (the bug diverged to ~1.5e13 px).
    assert result.stereo_rms < 2.0, (
        f"wide stereo RMS {result.stereo_rms:.3g} px diverged (expected sub-2 px)")

    # The recovered intrinsics must pass the shipped calib_check (the real device hit
    # "L pixel aspect strongly non-square" -- a runaway-fx symptom -- which must be gone).
    calib = StereoCalib.from_json(calib_to_dict(result, IMAGE_SIZE))
    fails = [c for c in run_checks(calib, reader=None) if c.status == FAIL]
    assert not fails, "wide solve FAILED calib_check:\n" + "\n".join(
        f"  {c.name}: {c.measured} -- {c.note}" for c in fails)

    print(f"[ok] WIDE-fisheye recovery: fx_l={fx_l:.3f} fx_r={fx_r:.3f} (GT 260/259, "
          f"NOT 1884), baseline={base_mm:.3f} mm (GT 75), stereo_rms="
          f"{result.stereo_rms:.4f} px, n_views_used={result.n_views_used}, "
          f"flags={result.calibrate_flags}, calib_check 0 FAIL")


# --------------------------------------------------------------------------- #
# Gate 1d: L<->R corner-ORDER reconciliation -- the PRIMARY real-device garbage root
# cause the prior fix MISSED. cv2.findChessboardCorners runs INDEPENDENTLY per image,
# and a cols x rows board has a 180-degree corner-order ambiguity, so a board imaged at
# different in-plane rotations on the two cameras can return the RIGHT corners in the
# fully-REVERSED order relative to the LEFT. Fed straight to stereoCalibrate, the
# mismatched object[k]/left[k] vs right[k] correspondence is "explained" as a
# ~180-degree inter-camera rotation and a runaway ~1 m baseline -- exactly the reported
# `baseline 961 mm`, `R ~ 168 deg`. This gate PROVES the reconcile_lr fix is load-bearing:
# WITHOUT it the solve diverges; WITH it the GT 75 mm baseline is recovered.
# --------------------------------------------------------------------------- #
def test_lr_corner_order_reconciliation() -> None:
    """Reverse the RIGHT corners per view (the real ambiguity); reconcile must cure it.

    Builds the noiseless synthetic stereo dataset, then 180-degree-REVERSES every
    right-camera corner array (``cr[::-1]``) -- the exact form ``findChessboardCorners``
    returns when it locks onto the board the opposite way round on the right camera.

      (a) WITHOUT reconciliation the solve DIVERGES: ``ok=False`` and the baseline blows
          far past the GT 75 mm (toward the reported ~1 m) -- proving the fix is
          load-bearing (mirrors the transpose/flip negative guards).
      (b) WITH ``reconcile_lr`` applied per view, the solver RECOVERS a sane ~75 mm
          baseline, a near-parallel extrinsic, and a low stereo RMS.

    A MIXED dataset (only SOME right views reversed) is also reconciled correctly, since
    ``reconcile_lr`` decides per pair -- the realistic case where the board's in-plane
    angle crosses the flip boundary on only some captures.
    """
    base_views = _project_views(noise_px=0.0)

    # --- (a) ALL right views reversed, NO reconciliation -> must diverge ---
    flipped = [(cl.copy(), cr[::-1].copy()) for (cl, cr) in base_views]
    bad = solve_stereo(
        flipped, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    bad_base_mm = bad.baseline_m * 1000.0
    assert not bad.ok, (
        "a 180-degree-reversed RIGHT corner order must NOT report a usable solve "
        f"(got ok=True, baseline={bad_base_mm:.1f} mm) -- reconciliation is the only fix")
    assert bad_base_mm > 200.0, (
        f"without reconciliation the baseline must DIVERGE far past 75 mm "
        f"(toward the reported ~1 m), got {bad_base_mm:.1f} mm -- the flip is not "
        f"actually corrupting the solve, so this test would not prove the fix")

    # --- (b) same data, WITH reconcile_lr per view -> must recover the GT ---
    recon = [reconcile_lr(cl, cr, PATTERN_COLS, PATTERN_ROWS)
             for (cl, cr) in flipped]
    good = solve_stereo(
        recon, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    _assert_recovers(good, k_tol_frac=0.01, baseline_tol_m=0.001,
                     rms_tol_px=0.05, label="LR-reconciled(all-flipped)")

    # --- MIXED: reverse only the even-indexed right views, then reconcile -> recover ---
    mixed = [(cl.copy(), (cr[::-1].copy() if i % 2 == 0 else cr.copy()))
             for i, (cl, cr) in enumerate(base_views)]
    mixed_recon = [reconcile_lr(cl, cr, PATTERN_COLS, PATTERN_ROWS)
                   for (cl, cr) in mixed]
    mixed_result = solve_stereo(
        mixed_recon, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    assert mixed_result.ok, (
        f"mixed-flip data must recover after per-pair reconciliation: "
        f"{mixed_result.failure_reason}")
    mixed_base_mm = mixed_result.baseline_m * 1000.0
    assert abs(mixed_base_mm - 75.0) <= 1.0, (
        f"mixed-flip reconciled baseline {mixed_base_mm:.3f} mm not within 1 mm of GT 75")

    print(f"[ok] L<->R corner-order reconciliation: WITHOUT it baseline DIVERGED to "
          f"{bad_base_mm:.1f} mm (ok={bad.ok}); WITH reconcile_lr recovered "
          f"{good.baseline_m * 1000:.3f} mm (GT 75, stereo_rms={good.stereo_rms:.4f} px); "
          f"mixed-flip recovered {mixed_base_mm:.3f} mm")


def test_collector_reconciles_flipped_right() -> None:
    """The COLLECTOR reconciles a per-view L<->R flip before it stores the pair.

    The reconciliation must live in the COLLECTION layer so EVERY accepted view's (L,R)
    corners correspond by the time they reach the solve -- not only when a caller invokes
    ``reconcile_lr`` by hand. We monkeypatch the collector's detector so the RIGHT camera
    always returns its corners 180-degree-REVERSED (the ambiguity), feed diverse tilted
    boards until complete, then solve ``collector.views`` directly: a correct collector
    yields a sane ~75 mm baseline; an un-reconciled one would diverge.
    """
    import sky.calib.collector as collector_mod

    coll = StereoCheckerboardCollector(
        PATTERN_COLS, PATTERN_ROWS, IMAGE_SIZE,
        cfg=CollectorConfig(n_target=6))

    real_detect = collector_mod.detect_corners
    call = {"n": 0}

    def detect_flipping_right(gray, cols, rows):
        # Detect normally, but REVERSE every SECOND call (the right camera of each
        # feed()) -- simulating findChessboardCorners returning the opposite ordering on
        # the right image. feed() calls detect_corners L then R, so odd calls are R.
        corners = real_detect(gray, cols, rows)
        call["n"] += 1
        if corners is not None and call["n"] % 2 == 0:
            return corners[::-1].copy()
        return corners

    collector_mod.detect_corners = detect_flipping_right
    try:
        specs = [
            (25.0, 0.0, (0.0, 0.0), 1.0),
            (-25.0, 5.0, (120.0, 0.0), 0.95),
            (0.0, 25.0, (-120.0, 0.0), 0.90),
            (20.0, -20.0, (0.0, 80.0), 0.85),
            (-18.0, 18.0, (0.0, -80.0), 0.80),
            (30.0, 10.0, (100.0, 60.0), 0.75),
            (-22.0, -12.0, (-100.0, -60.0), 0.70),
        ]
        for tilt_x, tilt_y, shift, scale in specs:
            f = _render_tilted_board_frame(tilt_x, tilt_y, shift, scale)
            coll.feed(f, f)
            if coll.complete:
                break
        assert coll.complete, "tilted sweep should complete even with the R flip"
        result = solve_stereo(
            coll.views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    finally:
        collector_mod.detect_corners = real_detect

    # The board here is fronto-rendered (same image to both cameras), so the recovered
    # baseline is ~0 and the extrinsic ~identity; the load-bearing assertion is that the
    # collector did NOT let a 180-flip through to a ~1 m divergence / ~180-degree rotation.
    base_mm = result.baseline_m * 1000.0
    rot_deg = np.degrees(np.arccos(np.clip((np.trace(result.R) - 1) / 2, -1.0, 1.0)))
    assert base_mm < 90.0 and rot_deg < 5.0, (
        f"collector failed to reconcile the R flip: baseline={base_mm:.1f} mm "
        f"rot={rot_deg:.1f} deg (an un-reconciled flip gives ~1 m / ~180 deg)")
    print(f"[ok] collector reconciliation: even with the RIGHT detector 180-reversed, "
          f"collector.views solve to baseline={base_mm:.2f} mm, inter-cam rot="
          f"{rot_deg:.2f} deg (NO ~1 m / ~180-deg divergence)")


def test_outlier_view_rejected() -> None:
    """A single CORRUPTED view is rejected by per-view gating; the solve still recovers.

    One mis-detected board (here: view 5's RIGHT corners NON-RIGIDLY scrambled -- a
    nonlinear per-corner radial stretch + jitter, the way a detector latching onto the
    wrong saddle points warps the grid) cannot be absorbed by a rigid pose, so it
    inflates that view's reprojection RMS. Without gating it would pull the whole fit
    off; we assert (a) the solve still converges, (b) it dropped exactly the bad view
    (``n_views_used < total``), and (c) fx + baseline are still recovered near the GT.
    A pure rigid pixel SHIFT would NOT test the gate -- cv2 just reads it as a board
    translation -- which is why the corruption here is deliberately non-rigid.
    """
    views = _project_wide_views()
    total = len(views)
    bad_idx = 5
    cl, cr = views[bad_idx]
    crd = cr.astype(np.float64)
    # Non-rigid radial scramble about the image centre + small jitter (deterministic).
    centre = np.array([IMAGE_SIZE[0] / 2.0, IMAGE_SIZE[1] / 2.0])
    rel = crd - centre
    stretch = 1.0 + 0.15 * np.sin(np.linalg.norm(rel, axis=1) / 30.0)
    jitter = np.random.default_rng(0).normal(0.0, 3.0, crd.shape)
    cr_bad = (centre + rel * stretch[:, None] + jitter).astype(np.float32)
    views[bad_idx] = (cl, cr_bad)

    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)

    assert result.ok, f"solve should still converge after gating: {result.failure_reason}"
    assert result.n_views_used < total, (
        f"the corrupted view must be dropped: n_views_used={result.n_views_used} "
        f"== total {total} (outlier NOT rejected)")
    assert result.n_views_used >= total - 2, (
        f"only the bad view(s) should be dropped, kept {result.n_views_used}/{total}")
    # Despite the injected outlier, fx + baseline are still recovered near the GT.
    fx_l = float(result.K_l[0, 0])
    assert abs(fx_l - 260.0) / 260.0 <= 0.03, (
        f"fx not recovered after gating: fx_l={fx_l:.2f} vs GT 260")
    base_mm = result.baseline_m * 1000.0
    assert abs(base_mm - 75.0) <= 8.0, (
        f"baseline not recovered after gating: {base_mm:.2f} mm vs GT 75 mm")
    print(f"[ok] outlier rejection: injected a non-rigidly-scrambled RIGHT view "
          f"({bad_idx}), solver kept {result.n_views_used}/{total} clean views, still "
          f"recovered fx_l={fx_l:.3f} (GT 260) baseline={base_mm:.3f} mm (GT 75)")


def test_too_few_clean_views_fails_honestly() -> None:
    """When the data is mostly junk, the solve FAILS honestly (ok=False), not garbage.

    Corrupt MOST views' RIGHT corners with a large NON-RIGID per-corner scramble (a
    rigid shift would be absorbed as a pose and not flagged; this genuinely destroys
    the grid). The solver must return ``ok=False`` with a clear reason rather than an
    implausible-but-usable calibration -- the wizard's honest-fail path. The failure
    may surface EITHER as "too few clean views ... recapture" (per-view gating dropped
    them) OR as "implausible solve (did not converge)" (the sanity floor caught the
    diverged stereo RMS the surviving junk produced) -- both are honest non-saves.
    """
    views = _project_wide_views()
    # Wreck all but 3 views' RIGHT corners with a HARD non-rigid radial scramble.
    centre = np.array([IMAGE_SIZE[0] / 2.0, IMAGE_SIZE[1] / 2.0])
    rng = np.random.default_rng(99)
    for i in range(len(views) - 3):
        cl, cr = views[i]
        crd = cr.astype(np.float64)
        rel = crd - centre
        stretch = 1.0 + 0.40 * np.sin(np.linalg.norm(rel, axis=1) / 20.0)
        jitter = rng.normal(0.0, 8.0, crd.shape)
        views[i] = (cl, (centre + rel * stretch[:, None] + jitter).astype(np.float32))

    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    assert not result.ok, "a mostly-corrupt dataset must NOT report a usable solve"
    reason = result.failure_reason.lower()
    assert ("recapture" in reason or "did not converge" in reason), (
        f"failure must carry an honest reason, got: {result.failure_reason!r}")
    print(f"[ok] honest fail: {len(views)} views mostly corrupted -> ok=False "
          f"(n_used={result.n_views_used}), reason={result.failure_reason!r}")


def test_min_clean_views_recapture_path() -> None:
    """The 'too few clean views -> recapture' BRANCH specifically (per-view gating).

    A small dataset (9 views) with 2 views whose corners are PURE GARBAGE (random
    in-frame points -- the cleanest model of a totally mis-detected board): the
    per-view gate drops them (and the views they contaminate), leaving FEWER than
    :data:`_MIN_CLEAN_VIEWS`, so the solver returns the explicit "recapture" reason.
    This exercises the gating branch directly (distinct from the sanity-floor branch in
    ``test_too_few_clean_views_fails_honestly``).
    """
    from sky.calib.solve import _MIN_CLEAN_VIEWS
    views = _project_wide_views()[: _MIN_CLEAN_VIEWS + 1]   # 9 views
    rng = np.random.default_rng(5)
    n_corners = PATTERN_COLS * PATTERN_ROWS
    for i in (0, 2):                                        # 2 totally-garbage views
        cl, _ = views[i]
        garbage = np.column_stack([
            rng.uniform(0, IMAGE_SIZE[0], n_corners),
            rng.uniform(0, IMAGE_SIZE[1], n_corners)]).astype(np.float32)
        views[i] = (cl, garbage)

    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)
    assert not result.ok, "with < min clean views the solve must fail"
    assert "recapture" in result.failure_reason.lower(), result.failure_reason
    assert result.n_views_used < _MIN_CLEAN_VIEWS, (
        f"recapture branch must report < {_MIN_CLEAN_VIEWS} clean views, "
        f"got {result.n_views_used}")
    print(f"[ok] recapture branch: {len(views)} views, 2 garbage -> "
          f"{result.n_views_used} clean (< {_MIN_CLEAN_VIEWS}) -> ok=False, "
          f"reason={result.failure_reason!r}")


def test_dump_roundtrip() -> None:
    """``solve_stereo(dump_path=...)`` writes a reloadable .npz of the captured views.

    Proves the debug dump (so the operator can send us REAL data) is wired and that the
    .npz round-trips the object/image points, board geometry, image size, and result.
    """
    from sky.calib.solve import dump_views

    views = _project_wide_views()
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "oakd_calib_views_15.npz"
        result = solve_stereo(
            views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE,
            dump_path=path)
        assert path.exists(), "solve with dump_path must write the .npz"
        data = np.load(path, allow_pickle=False)
        # Geometry + sizes round-trip.
        assert int(data["pattern_cols"]) == PATTERN_COLS
        assert int(data["pattern_rows"]) == PATTERN_ROWS
        assert abs(float(data["square_size_m"]) - SQUARE_SIZE_M) < 1e-12
        assert list(data["image_size"]) == list(IMAGE_SIZE)
        # Per-view buffers: (V, N, k) stacks for object + L/R image points.
        n_used = result.n_views_used
        n_corners = PATTERN_COLS * PATTERN_ROWS
        assert data["img_left"].shape == (n_used, n_corners, 2), data["img_left"].shape
        assert data["img_right"].shape == (n_used, n_corners, 2)
        assert data["object_points"].shape == (n_used, n_corners, 3)
        # Result fields are stored too.
        assert np.allclose(data["K_l"], result.K_l)
        assert bool(data["ok"]) == result.ok

        # dump_views can also be called standalone (the path the wizard logs).
        obj = [data["object_points"][i].reshape(-1, 1, 3) for i in range(n_used)]
        il = [data["img_left"][i].reshape(-1, 1, 2) for i in range(n_used)]
        ir = [data["img_right"][i].reshape(-1, 1, 2) for i in range(n_used)]
        p2 = Path(tmp) / "manual.npz"
        written = dump_views(p2, obj, il, ir, PATTERN_COLS, PATTERN_ROWS,
                             SQUARE_SIZE_M, IMAGE_SIZE, result)
        assert written.exists()
    print(f"[ok] dump round-trip: solve(dump_path=...) wrote {n_used} views + result "
          f"to .npz, reloaded + standalone dump_views() OK")


# --------------------------------------------------------------------------- #
# Gate 1b: PROVE the recovery check has teeth -- a corrupted extrinsic must FAIL.
# We take the correctly solved result and inject the two classic silent bugs a
# LEFT<->RIGHT mix-up produces (a TRANSPOSED rotation and a NEGATED translation),
# then assert _assert_recovers now raises. Without this, a passing recovery test
# could still be satisfied by a transpose/flip the thresholds happened to admit.
# --------------------------------------------------------------------------- #
def _solve_clean():
    """Solve the noiseless synthetic rig -- the correct result to then corrupt."""
    views = _project_views(noise_px=0.0)
    return solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)


def test_extrinsic_transpose_is_caught() -> None:
    """Inject ``R := R.T`` into a correct solve -> the recovery check must FAIL.

    At the 2.5 deg GT rotation, ``||R.T - R|| ~= 0.087`` swamps the tightened
    ``R_err < 5e-3`` gate, so a real LEFT->RIGHT transpose bug in ``solve.py`` can no
    longer slip through. (At the old 0.8 deg GT, ``||R.T - R|| ~= 0.028`` -- below the
    old 5e-2 gate -- which is exactly the hole this sub-test closes.)
    """
    good = _solve_clean()
    # Sanity: the transpose really is geometrically distinct at this GT rotation.
    transpose_gap = float(np.linalg.norm(good.R.T - good.R))
    assert transpose_gap > 5e-3, (
        f"GT rotation too small to distinguish a transpose: "
        f"||R.T-R||={transpose_gap:.4e} <= 5e-3 (raise the GT inter-cam angle)")

    bad = dataclasses.replace(good, R=good.R.T.copy())
    try:
        _assert_recovers(bad, k_tol_frac=0.01, baseline_tol_m=0.001,
                         rms_tol_px=0.05, label="transposed-R(should-fail)")
    except AssertionError as exc:
        assert "extrinsic mismatch" in str(exc), (
            f"transpose was caught, but not by the rotation arm: {exc}")
        print(f"[ok] transpose guard: injecting R:=R.T (||R.T-R||={transpose_gap:.4e}) "
              f"correctly FAILS the recovery check")
        return
    raise AssertionError(
        "recovery check PASSED a transposed extrinsic R -- the rotation guard is "
        "toothless (a LEFT<->RIGHT transpose bug would slip through)")


def test_extrinsic_flip_is_caught() -> None:
    """Inject ``T := -T`` (the right->left inverse) -> the flip-guard must FAIL.

    Complements the transpose test: a pure-translation sign error (the direction-blind
    silent bug the flip-guard was built for) must trip the ``t_err < t_err_if_flipped``
    arm, not pass unnoticed.
    """
    good = _solve_clean()
    bad = dataclasses.replace(good, T=(-good.T).copy())
    try:
        _assert_recovers(bad, k_tol_frac=0.01, baseline_tol_m=0.001,
                         rms_tol_px=0.05, label="negated-T(should-fail)")
    except AssertionError as exc:
        assert "FLIPPED" in str(exc), (
            f"negated T was caught, but not by the flip-guard arm: {exc}")
        print("[ok] flip guard: injecting T:=-T (right->left inverse) correctly "
              "FAILS the recovery check")
        return
    raise AssertionError(
        "recovery check PASSED a negated translation T -- the flip-guard is toothless")


# --------------------------------------------------------------------------- #
# Gate 2: collector logic. We render REAL boards (Phase-1 generator) and warp them
# to synthetic poses so detect_corners runs the genuine cv2 path end-to-end.
# --------------------------------------------------------------------------- #
def _render_board_frame(homography_shift: tuple[float, float],
                        scale: float) -> np.ndarray:
    """Render the Phase-1 board onto a 640x400 canvas at a given offset + scale.

    Returns a uint8 (400,640) frame with the (detectable) board placed inside it.
    ``homography_shift`` moves the board centroid; ``scale`` changes apparent size.
    """
    board = make_checkerboard(PATTERN_COLS, PATTERN_ROWS, square_px=30,
                              margin_squares=1.0)
    bh, bw = board.shape
    # Scale the board.
    new_w = max(1, int(bw * scale))
    new_h = max(1, int(bh * scale))
    board_s = cv2.resize(board, (new_w, new_h), interpolation=cv2.INTER_AREA)

    canvas = np.full((IMAGE_SIZE[1], IMAGE_SIZE[0]), 255, dtype=np.uint8)
    dx, dy = homography_shift
    x0 = int((IMAGE_SIZE[0] - new_w) / 2 + dx)
    y0 = int((IMAGE_SIZE[1] - new_h) / 2 + dy)
    x0 = max(0, min(x0, IMAGE_SIZE[0] - new_w))
    y0 = max(0, min(y0, IMAGE_SIZE[1] - new_h))
    canvas[y0:y0 + new_h, x0:x0 + new_w] = board_s
    return canvas


def _render_tilted_board_frame(tilt_x_deg: float, tilt_y_deg: float,
                               shift: tuple[float, float] = (0.0, 0.0),
                               scale: float = 1.0) -> np.ndarray:
    """Render the board under a perspective TILT so it is NOT fronto-parallel.

    A pure ``_render_board_frame`` is always square-on (skew ~0): perfect for the
    translation/scale diversity axes but useless for exercising the new tilt-coverage
    gate. Here we warp the scaled board with a homography that foreshortens it about
    the X (``tilt_x_deg``) and Y (``tilt_y_deg``) axes, so ``detect_corners`` returns
    a genuinely oblique corner set with elevated skew -- the only way the collector's
    ``skew_ok`` coverage gate can be satisfied.
    """
    board = make_checkerboard(PATTERN_COLS, PATTERN_ROWS, square_px=30,
                              margin_squares=1.0)
    bh, bw = board.shape
    new_w = max(1, int(bw * scale))
    new_h = max(1, int(bh * scale))
    board_s = cv2.resize(board, (new_w, new_h), interpolation=cv2.INTER_AREA)

    # Foreshorten the four corners: tilt about X shrinks the vertical extent of one
    # edge, tilt about Y the horizontal -- a cheap, detectable perspective oblique.
    src = np.float32([[0, 0], [new_w, 0], [new_w, new_h], [0, new_h]])
    tx = np.tan(np.deg2rad(tilt_x_deg))
    ty = np.tan(np.deg2rad(tilt_y_deg))
    dx_warp = new_w * 0.5 * abs(ty)
    dy_warp = new_h * 0.5 * abs(tx)
    dst = np.float32([
        [dx_warp, dy_warp],
        [new_w - dx_warp, 0.0 if tilt_x_deg >= 0 else dy_warp * 2.0],
        [new_w, new_h - dy_warp],
        [dx_warp if tilt_y_deg >= 0 else 0.0, new_h],
    ])
    h_mat = cv2.getPerspectiveTransform(src, dst)
    warped = cv2.warpPerspective(board_s, h_mat, (new_w, new_h), borderValue=255)

    canvas = np.full((IMAGE_SIZE[1], IMAGE_SIZE[0]), 255, dtype=np.uint8)
    sx, sy = shift
    x0 = int((IMAGE_SIZE[0] - new_w) / 2 + sx)
    y0 = int((IMAGE_SIZE[1] - new_h) / 2 + sy)
    x0 = max(0, min(x0, IMAGE_SIZE[0] - new_w))
    y0 = max(0, min(y0, IMAGE_SIZE[1] - new_h))
    canvas[y0:y0 + new_h, x0:x0 + new_w] = warped
    return canvas


def test_collector_logic() -> None:
    """Accepts diverse views, rejects a near-duplicate + a one-camera failure."""
    coll = StereoCheckerboardCollector(
        PATTERN_COLS, PATTERN_ROWS, IMAGE_SIZE)

    # A clearly diverse first view (centred, full size).
    f0 = _render_board_frame((0.0, 0.0), scale=1.0)
    s0 = coll.feed(f0, f0)
    assert s0.found_left and s0.found_right, "view 0 must detect in both"
    assert s0.accepted, f"view 0 should be accepted (reason: {s0.reason})"
    assert coll.accepted_count == 1

    # Near-duplicate of the last accepted view -> REJECTED by the diversity gate.
    s_dup = coll.feed(f0, f0)
    assert not s_dup.accepted, "a near-duplicate must be rejected"
    assert "similar" in s_dup.reason.lower(), s_dup.reason
    assert coll.accepted_count == 1, "duplicate must not grow the accepted set"

    # One-camera detection failure -> REJECTED (right frame is blank white).
    blank = np.full((IMAGE_SIZE[1], IMAGE_SIZE[0]), 255, dtype=np.uint8)
    f_shift = _render_board_frame((120.0, 60.0), scale=1.0)
    s_onecam = coll.feed(f_shift, blank)
    assert not s_onecam.accepted, "one-camera failure must be rejected"
    assert not s_onecam.found_right and s_onecam.found_left, s_onecam.reason
    assert "RIGHT" in s_onecam.reason, s_onecam.reason
    assert coll.accepted_count == 1

    # A genuinely different pose (shifted + smaller) -> ACCEPTED.
    s_diverse = coll.feed(f_shift, f_shift)
    assert s_diverse.accepted, f"diverse view should be accepted: {s_diverse.reason}"
    assert coll.accepted_count == 2
    print(f"[ok] collector: accept diverse, reject duplicate "
          f"(novelty {s_dup.novelty:.3f} < {coll.cfg.min_novelty}), "
          f"reject one-camera failure")


def test_collector_fronto_parallel_count_not_complete() -> None:
    """All-fronto-parallel sweep reaches n_target accepted but is NOT complete.

    This is the Fix-2 guard: a square-on board slid around the frame satisfies the
    per-frame (centroid+size) novelty on TRANSLATION alone, so it can hit the count
    target with skew ~0 -- leaving focal length weakly observable. Completion must be
    withheld (``count_ok`` True, ``skew_ok`` False) and the status must tell the
    operator to tilt the board.
    """
    cfg_target = 6
    coll = StereoCheckerboardCollector(
        PATTERN_COLS, PATTERN_ROWS, IMAGE_SIZE,
        cfg=CollectorConfig(n_target=cfg_target))

    # Distinct (shift, scale) FRONTO-PARALLEL poses: vary translation + depth only.
    poses = [
        ((0.0, 0.0), 1.0),
        ((130.0, 0.0), 1.0),
        ((-130.0, 0.0), 1.0),
        ((0.0, 90.0), 0.85),
        ((0.0, -90.0), 0.85),
        ((110.0, 70.0), 0.7),
        ((-110.0, -70.0), 0.7),
    ]
    last = None
    for shift, scale in poses:
        f = _render_board_frame(shift, scale)
        last = coll.feed(f, f)
        if coll.complete:
            break

    assert last is not None
    assert coll.count_ok, f"fronto sweep should reach the count: {coll.accepted_count}"
    assert coll.accepted_count >= cfg_target
    assert not coll.skew_ok, (
        f"fronto-parallel sweep must NOT satisfy tilt coverage "
        f"(skew_range={last.coverage.skew_range:.4f} >= {coll.cfg.min_skew_spread})")
    assert not coll.complete, "all-fronto-parallel data must NOT report complete"
    assert last.count_ok and not last.skew_ok and not last.complete
    assert "tilt" in last.reason.lower(), last.reason
    cov = last.coverage
    print(f"[ok] collector fronto-parallel: {coll.accepted_count} accepted, "
          f"count_ok={coll.count_ok} but skew_ok={coll.skew_ok} -> NOT complete "
          f"(skew_range={cov.skew_range:.4f} < {coll.cfg.min_skew_spread})")


def test_collector_tilted_reaches_complete() -> None:
    """A genuinely TILTED + diverse sweep reaches n_target AND completes.

    Same count target as the fronto-parallel test, but every view is perspective-
    tilted (high skew) and additionally translated/scaled so each clears the novelty
    gate. This must satisfy BOTH arms -- count and tilt coverage -- and report
    complete, then stop over-collecting.
    """
    cfg_target = 6
    coll = StereoCheckerboardCollector(
        PATTERN_COLS, PATTERN_ROWS, IMAGE_SIZE,
        cfg=CollectorConfig(n_target=cfg_target))

    # (tilt_x_deg, tilt_y_deg, shift, scale): tilt for skew coverage, plus a
    # translation/scale spread so each view is novel on more than one axis.
    specs = [
        (25.0, 0.0, (0.0, 0.0), 1.0),
        (-25.0, 5.0, (120.0, 0.0), 0.95),
        (0.0, 25.0, (-120.0, 0.0), 0.90),
        (20.0, -20.0, (0.0, 80.0), 0.85),
        (-18.0, 18.0, (0.0, -80.0), 0.80),
        (30.0, 10.0, (100.0, 60.0), 0.75),
        (-22.0, -12.0, (-100.0, -60.0), 0.70),
    ]
    last = None
    for tilt_x, tilt_y, shift, scale in specs:
        f = _render_tilted_board_frame(tilt_x, tilt_y, shift, scale)
        last = coll.feed(f, f)
        if coll.complete:
            break

    assert last is not None
    assert coll.count_ok, f"tilted sweep should reach the count: {coll.accepted_count}"
    assert coll.skew_ok, (
        f"tilted sweep must satisfy tilt coverage "
        f"(skew_range={last.coverage.skew_range:.4f} >= {coll.cfg.min_skew_spread})")
    assert coll.complete, f"tilted data must complete: {coll.accepted_count}/{cfg_target}"
    assert coll.accepted_count == cfg_target

    # Once complete, further feeds are ignored (no over-collection).
    f_extra = _render_tilted_board_frame(25.0, 0.0, (0.0, 0.0), 1.0)
    s_after = coll.feed(f_extra, f_extra)
    assert not s_after.accepted and s_after.complete
    assert coll.accepted_count == cfg_target
    cov = s_after.coverage
    print(f"[ok] collector tilted: reached {cfg_target}/{cfg_target}, "
          f"count_ok={coll.count_ok} skew_ok={coll.skew_ok} -> complete "
          f"(coverage cx={cov.centroid_x:.3f} cy={cov.centroid_y:.3f} "
          f"size={cov.size:.3f} skew_range={cov.skew_range:.4f})")


# --------------------------------------------------------------------------- #
# Gate 3: writer round-trip (cm/m factor) + calib_check verdict.
# --------------------------------------------------------------------------- #
def test_writer_roundtrip_and_calib_check() -> None:
    """Write a solved calib, reload via StereoCalib.from_json, prove cm/m + PASS."""
    views = _project_views(noise_px=0.0)
    result = solve_stereo(
        views, PATTERN_COLS, PATTERN_ROWS, SQUARE_SIZE_M, IMAGE_SIZE)

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "calib.json"
        written = write_calib_json(result, IMAGE_SIZE, path)
        assert written.exists()

        data = json.loads(written.read_text())
        calib = StereoCalib.from_json(data)

        # cm/m ROUND-TRIP PROOF: the reloaded baseline (loader did *0.01 on the cm
        # we wrote) must equal the solved baseline to 1e-6 m. A missing m->cm
        # multiply in the writer would make this 100x too small and FAIL here.
        assert abs(calib.baseline_m - result.baseline_m) < 1e-6, (
            f"baseline round-trip broken: reloaded {calib.baseline_m * 1000:.6f} mm "
            f"vs solved {result.baseline_m * 1000:.6f} mm "
            f"(cm/m factor bug?)")

        # The raw JSON translation must be in CENTIMETRES (~7.5), not metres.
        T_json = np.asarray(data["T_left_right"], dtype=np.float64).reshape(4, 4)
        json_t_norm = float(np.linalg.norm(T_json[:3, 3]))
        assert abs(json_t_norm - result.baseline_m * 100.0) < 1e-6, (
            f"JSON translation should be cm (~{result.baseline_m * 100:.3f}), "
            f"got {json_t_norm:.3f}")

        # Intrinsics round-trip exactly (fx/fy/cx/cy).
        assert abs(calib.left.fx - result.K_l[0, 0]) < 1e-9
        assert abs(calib.left.cy - result.K_l[1, 2]) < 1e-9
        assert abs(calib.right.fx - result.K_r[0, 0]) < 1e-9

        # END-TO-END TIE-IN: run the shipped calib_check suite on the parsed calib.
        # A good solve must produce NO FAIL rows (WARN is allowed: IMU absent etc.).
        checks = run_checks(calib, reader=None)
        fails = [c for c in checks if c.status == FAIL]
        assert not fails, "calib_check FAILED rows:\n" + "\n".join(
            f"  {c.name}: {c.measured} (exp {c.expected}) -- {c.note}" for c in fails)

    # Also prove calib_to_dict (in-memory) matches the on-disk structure.
    d_mem = calib_to_dict(result, IMAGE_SIZE)
    assert "intrinsics_left" in d_mem and "T_left_right" in d_mem

    print(f"[ok] writer round-trip: solved baseline {result.baseline_m * 1000:.6f} mm "
          f"-> JSON {json_t_norm:.4f} cm -> reloaded {calib.baseline_m * 1000:.6f} mm "
          f"(|err| < 1e-6 m)")
    print(f"[ok] calib_check verdict: PASS ({len(checks)} checks, 0 FAIL)")


# --------------------------------------------------------------------------- #
# cv2 hygiene: importing the calib package must NOT pull OpenCV.
# --------------------------------------------------------------------------- #
def test_package_import_is_cv2_free() -> None:
    """A bare `import ui.mathlib.calib` (+ submodules) must not load cv2.

    Runs in a clean subprocess so this test process's own `import cv2` (the oracle)
    cannot mask the result.
    """
    code = (
        "import sys; "
        "import ui.mathlib.calib; "
        "import sky.calib.detect; "
        "import sky.calib.collector; "
        "import sky.calib.solve; "
        "import sky.calib.writer; "
        "assert 'cv2' not in sys.modules, "
        "'cv2 leaked into the calib import path'; "
        "print('clean')"
    )
    import subprocess
    proc = subprocess.run(
        [sys.executable, "-W", "error", "-c", code],
        cwd=str(Path(__file__).resolve().parents[2]),
        capture_output=True, text=True)
    assert proc.returncode == 0, (
        f"cv2-free import check failed:\nSTDOUT:{proc.stdout}\nSTDERR:{proc.stderr}")
    assert proc.stdout.strip() == "clean"
    print("[ok] bare `import ui.mathlib.calib` (+ submodules) does NOT load cv2 "
          "(under -W error)")


def main() -> int:
    test_package_import_is_cv2_free()
    test_synthetic_recovery_noiseless()
    test_synthetic_recovery_noisy()
    test_wide_fisheye_recovery()
    test_lr_corner_order_reconciliation()
    test_collector_reconciles_flipped_right()
    test_outlier_view_rejected()
    test_too_few_clean_views_fails_honestly()
    test_min_clean_views_recapture_path()
    test_dump_roundtrip()
    test_extrinsic_transpose_is_caught()
    test_extrinsic_flip_is_caught()
    test_collector_logic()
    test_collector_fronto_parallel_count_not_complete()
    test_collector_tilted_reaches_complete()
    test_writer_roundtrip_and_calib_check()
    print("\nALL CALIB SOLVE SELFTESTS PASSED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
